"""Initial schema fixed

Revision ID: 2329a9dfc221
Revises: 
Create Date: 2025-11-24 02:08:38.070737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '2329a9dfc221'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hours_of_operation', sqlite.JSON(), nullable=True),
    sa.Column('services', sqlite.JSON(), nullable=True),
    sa.Column('faq', sqlite.JSON(), nullable=True),
    sa.Column('pos_system', sa.String(length=50), nullable=True),
    sa.Column('pos_credentials', sqlite.JSON(), nullable=True),
    sa.Column('calendar_system', sa.String(length=50), nullable=True),
    sa.Column('calendar_credentials', sqlite.JSON(), nullable=True),
    sa.Column('primary_language', sa.String(length=10), nullable=True),
    sa.Column('supported_languages', sqlite.JSON(), nullable=True),
    sa.Column('greeting_message', sqlite.JSON(), nullable=True),
    sa.Column('voice_settings', sqlite.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('calls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('call_sid', sa.String(length=255), nullable=False),
    sa.Column('caller_number', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('detected_language', sa.String(length=10), nullable=True),
    sa.Column('intent', sa.String(length=100), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('transcript', sqlite.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.String(length=100), nullable=True),
    sa.Column('booking_id', sa.String(length=36), nullable=True),
    sa.Column('escalated_to_human', sa.Boolean(), nullable=True),
    sa.Column('escalation_reason', sa.String(length=255), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('response_time_avg_ms', sa.Float(), nullable=True),
    sa.Column('customer_satisfaction', sa.Integer(), nullable=True),
    sa.Column('recording_url', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_sid')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('bookings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=True),
    sa.Column('call_id', sa.String(length=36), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_phone', sa.String(length=20), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('confirmation_code', sa.String(length=20), nullable=True),
    sa.Column('booking_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    op.drop_table('users')
    op.drop_table('calls')
    op.drop_table('businesses')
    # ### end Alembic commands ###
