db-uri = "postgres://zenith:zenith@127.0.0.1:5432/zenith"
db-schemas = "public"
db-anon-role = "anon"
jwt-secret = "local-test-jwt-secret-32-bytes-minimum!!"
jwt-role-claim-key = ".role"
server-port = 3000
